name: CI

on:
  workflow_dispatch:

jobs:
  cosignbinary:
    runs-on: ubuntu-latest
    steps:
      - name: Install Cosign
        uses: sigstore/cosign-installer@main
        with:
          cosign-release: 'v1.4.1'
      - name: Check install!
        run: cosign version
      - name: Fix cosign binary for root
        run: |
          cosign_bin="$HOME/.cosign/cosign"
          sudo ln -s $cosign_bin /usr/bin/cosign
      - run: sudo cosign version
