on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # undocumented OIDC support.
    env:
      COSIGN_EXPERIMENTAL: 1 # use keyless signing
      LUET_INSTALL_FROM_COS_REPO: true
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Install luet
        run: curl -s https://raw.githubusercontent.com/rancher-sandbox/cOS-toolkit/master/scripts/get_luet.sh | sudo -E bash
      - name: Install cosign
        run: sudo -E luet install -y toolchain/cosign
      - name: Build dockerfile
        run: |
          docker build . -t itxaka/test:latest
          docker push itxaka/test:latest
      - name: Cosign keyless
        run: |
          sudo -E bash -c "cosign sign itxaka/test:latest"
